# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/moto8937_o/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/moto8937_o

PRODUCT_COPY_FILES += \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/wlan/prima/ahannah_WCNSS_qcom_wlan_nv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/prima/ahannah_WCNSS_qcom_wlan_nv.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/wlan/prima/aljeter_WCNSS_qcom_wlan_nv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/prima/aljeter_WCNSS_qcom_wlan_nv.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/wlan/prima/hannah_WCNSS_qcom_wlan_nv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/prima/hannah_WCNSS_qcom_wlan_nv.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/wlan/prima/jeter_WCNSS_qcom_wlan_nv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/prima/jeter_WCNSS_qcom_wlan_nv.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/wlan/prima/nora_WCNSS_qcom_wlan_nv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/prima/nora_WCNSS_qcom_wlan_nv.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/FT8006U_Pramboot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/FT8006U_Pramboot.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/focaltech-ofilm-ft8006u-04-0001-hannah.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-ofilm-ft8006u-04-0001-hannah.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/focaltech-ofilm-ft8006u-05-0001-hannah.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-ofilm-ft8006u-05-0001-hannah.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/himax-djn-hx83102b-171110-0504-hannah.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-djn-hx83102b-171110-0504-hannah.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/himax-djn-hx83102b-171120-0604-hannah.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-djn-hx83102b-171120-0604-hannah.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/novatek_ts-djn-NT36525-180226-17-hannah.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-djn-NT36525-180226-17-hannah.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/novatek_ts-djn-NT36525-180410-18-hannah.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-djn-NT36525-180410-18-hannah.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/novatek_ts-tianma-NT36525-180131-23-hannah.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-tianma-NT36525-180131-23-hannah.bin \
    vendor/motorola/moto8937_o/proprietary/vendor/firmware/novatek_ts-tianma-NT36525-180312-25-hannah.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-tianma-NT36525-180312-25-hannah.bin
